### ISSUE TITLE
Get value of textfield after closure with custom view

### ISSUE THREAD

**Issue by OptimusKoala** [KyoheiG3/SimpleAlert#11]
I use a custom view with a textField and a TextView. I use a xib file just as you used in the exemple. 
But i can't catch value of my textField and textView after closure. 

How can I do this? 

`// Create view for pop up
 let myView = popUpView()

 // Print pop up
 let alert = SimpleAlert.Controller(view: myView.view, style: .Alert)
 alert.addAction(SimpleAlert.Action(title: "Cancel", style: .Cancel))
 alert.addAction(SimpleAlert.Action(title: "OK", style: .OK))
 presentViewController(alert, animated: true, completion: nil)`

**Comment by KyoheiG3** [comment]
If the view of popUpView is that it textview, It is possible and to do the following:

``` swift
alert.addAction(SimpleAlert.Action(title: "OK", style: .OK) { action in
    print("\(myView.view.text)")
})
```
