### ISSUE TITLE
No such module SimpleAlert

### ISSUE THREAD

**Issue by DominikButz** [KyoheiG3/SimpleAlert#12]
I'm getting this error message on the line
No such module SimpleAlert

import SimpleAlert

I tried adding the version number in the pod file, doesn't help... 

the pod installation worked correctly, no error message. Anyone else having this problem?

**Comment by DominikButz** [comment]
sorry, I hadn't seen this issue was posted before. True, it seems it compiles nevertheless.

**Comment by akabab** [comment]
@DominikButz close the issue if it's solved. Eventually indicate what was wrong.
