### ISSUE TITLE
can't modify message text

### ISSUE THREAD

**Issue by grantism** [KyoheiG3/SimpleAlert#14]
After initializing a simpleAlert controller, it is possible to change the title, but it is not possible to change the message.

This works:
`let alert = SimpleAlert.Controller(title: "blah", message: "blah", style: .Alert)`
`alert.title = "changed it"`

But this doesn't:
`let alert = SimpleAlert.Controller(title: "blah", message: "blah", style: .Alert)`
`alert.message = "changed it"`

For consistency & flexibility, it should be possible to set the message value in the same way as the title.

**Comment by KyoheiG3** [comment]
Oh, Sorry, It is a bug that title can be changed. Do you need the property to change message?
Thanks.

**Comment by grantism** [comment]
That makes sense. I was coming from the point of view of the standard `UIAlertController` & other UI items which allows changing the title and message properties after initialisation (More as a point of keeping consistency with other UI elements than anything else).

I suppose this issue should be 'Don't allow modification of title after initialisation' instead :)

**Comment by KyoheiG3** [comment]
Message text became to be able to modify in #32.
