### ISSUE TITLE
Show Data in CustomView 

### ISSUE THREAD

**Issue by Danielthenew** [KyoheiG3/SimpleAlert#15]
I want to make a Alert with a UITableView so i use this pod i have use this code (at the bottom) to show the Alert with the CustomView.  So TableView2Controller is my tableview but when it show the Alert it´s shows the TableView but no data in it (cells) . 
I have tried without the Alert  `self.showViewController(AlertView, sender: self)` it´s shows the data in the tableview so the problem must be in `let AlertTableView = SimpleAlert.Controller(view: AlertView.view, style: .Alert)` .  
In my another Alert i have a Button in the view, in my ViewController a Action from the Button and a print int it. When i show the Alert and klick the Button it´s print anything so i think it´s the same Problem like the tableviewalert. 

`       let storyboard = UIStoryboard(name: "TableView2Controller", bundle: nil)

```
    let AlertView = storyboard.instantiateViewControllerWithIdentifier("TableView2Controller") as! TableView2Controller

    let AlertTableView = SimpleAlert.Controller(view: AlertView.view, style: .Alert)

    showAlert(AlertTableView)` 
```

So have you an idea what can be the Problem hier ? Thanks for your Help.

**Comment by KyoheiG3** [comment]
It must be added to the UIViewController, maybe.

``` swift
let AlertTableView = SimpleAlert.Controller(view: AlertView.view, style: .Alert)
AlertTableView.addChildViewController(AlertView)
AlertView.didMoveToParentViewController(AlertTableView)
```

Pray that the bug does not occur :sweat:

**Comment by Danielthenew** [comment]
So it´s run, Thanks for your Help 😉
