### ISSUE TITLE
DatePicker in CustomAlert catch date from DatePicker

### ISSUE THREAD

**Issue by Danielthenew** [KyoheiG3/SimpleAlert#16]
Hey i use the CustomAlert for select and change an date. So when it´s show the Alert i select my date and then save it. Now i have a Problem on `AlertView.DatePicker.date` it´s give me always the topical date, so when i change the date in the Alert it´s have no effect. Have you a idea what can be the Problem? 

`   let AlertView = DateAlertController(nibName: "DateAlertController", bundle: nil)

```
                            let AlertDateView = SimpleAlert.Controller(view: AlertView.view, style: .Alert)
                            self.showAlert(AlertDateView)

                            let date = AlertView.DatePicker.date

                            PAlertdate = date`
```

Thanks for your Help :)

**Comment by akabab** [comment]
```
let date = AlertView.DatePicker.date
```
are you expecting here to create a reference to your datepicker date ? `Date` objects are value type (structures) in Swift (see. https://developer.apple.com/documentation/foundation/date)

try to access DatePicker.date at the moment you need it, or register to `.valueChanged` event

```swift
let datePicker = AlertView.DatePicker
datePicker.addTarget(self, action: #selector(ViewController.datePickerValueChanged(_:)), for: .valueChanged)
```
```swift
@objc func datePickerValueChanged(_ sender: UIDatePicker) {
  print(sender.date)
}
```
