### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by akabab** [KyoheiG3/SimpleAlert#19]

**Comment by KyoheiG3** [comment]
Wait for https://github.com/KyoheiG3/SimpleAlert/pull/20.

**Comment by yumsmools** [comment]
hi there,

Great control.
Any news when you'll release 2.0?

**Comment by KyoheiG3** [comment]
Hi guys
I have released [2.0.0](https://github.com/KyoheiG3/SimpleAlert/tree/2.0.0).
Thanks.
