### ISSUE TITLE
Autoresize

### ISSUE THREAD

**Issue by osipkat** [KyoheiG3/SimpleAlert#2]
I've made my CustomViewController to use in SimpleAlert. It contains label which is filled dynamically. But it doesn't autoresize. Height of SimpleAlert keeps the same as in my nib file. How to make it autoresize its height?

**Comment by KyoheiG3** [comment]
You can display a CustomView to call `init(view: UIView?, style: Style)`. that before it is necessary to set size of the CustomView to.
