### ISSUE TITLE
How to dismiss alertcontroller

### ISSUE THREAD

**Issue by rezasham** [KyoheiG3/SimpleAlert#24]
Keyboard is automatically shown as soon as the alertview with a textfield is used. this is covering the buttons (cancel button added to view) so not possible to dismiss the keyboard or cancel out and dismiss the entire view. 
1. How to remove auto selection on the textfield as the alertview is shown?
2. Possible to dismiss the alertview by tapping outside of the alertview?

R

**Comment by KyoheiG3** [comment]
Sorry but both impossible.
For question 2 try add `UITapGesture` to `AlertController` view. then call dismiss.

Thanks.
