### ISSUE TITLE
How can I change font of title in alert controller?

### ISSUE THREAD

**Issue by nalogowiec** [KyoheiG3/SimpleAlert#25]
I'm trying to modify the font of the title in alert controller. This is how I create it:

    `let alertController = AlertController(title: nil, message: "this could have some fancy font", style: .actionSheet)`
        
I know I can change the color of this font by:

        `alertController.view.tintColor = orangeColor`

but what about custom font?

**Comment by KyoheiG3** [comment]
Hi @nalogowiec
You can use `configureContentView` function.
It's available as function or closure. Please see an [example](https://github.com/KyoheiG3/SimpleAlert/blob/master/SimpleAlertExample/SimpleAlertExample/AlertController.swift).
