### ISSUE TITLE
How can I have a textfield multilines?

### ISSUE THREAD

**Issue by 94tinat** [KyoheiG3/SimpleAlert#26]
Hi!
I would insert a textfield on multilines as the second demo of this library.
How can I do that?

Thank for your help!

**Comment by fredjahanmanesh** [comment]
if you test the demo, you will realize that textfield dose not support multiline too, actually its a textfield , not a UITextView, i want this too

i found a solution, 
`let cancelAction = AlertAction(title: "cancel", style: .cancel, handler: nil)
    var addNewListAlert : AlertController!
    var btn_alert_saveButton : AlertAction!
    var txt_alert_content : UITextView?
    @IBAction func btn_addFunc(){
        //1. Create the alert controller.
         addNewListAlert = AlertController(title: "Give me your description ", message: "Say what you want", style: .alert)
        
        //2. Add the text field. You can configure it however you need.
        addNewListAlert.addTextFieldWithConfigurationHandler { (textField) in
            textField?.frame.size.height = 100
            textField?.backgroundColor = nil
            textField?.layer.borderColor = nil
            textField?.layer.borderWidth = 0
            textField?.clipsToBounds = true
        }
        //init textView
        txt_alert_content = UITextView(frame: .zero)
        
        //give it some backgroundColor and font
        self.txt_alert_content!.backgroundColor = UIColor.gray
        self.txt_request!.font = UIFont.mediumFont()

        //Add textview as subview of textfield
        addNewListAlert.configContentView = { cview in
            //set textview size and origin equal to alert textfield
            self.txt_alert_content!.frame = cview!.subviews[0].subviews[2].subviews[0].frame
            cview!.subviews[0].subviews[2].subviews[0].isHidden = true

            //add it above textfield in textfield container
            cview?.subviews[0].subviews[2].insertSubview(self.txt_alert_content!, at: 1)
        }
        //init SaveButton
        btn_alert_saveButton = AlertAction(title: "Save", style: .default,dismissesAlert:false, handler: { [weak addNewListAlert] (_) in
        })

        // 3. Grab the value from the text field, and print it when the user clicks OK.
        addNewListAlert.addAction(btn_alert_saveButton)
        btn_alert_saveButton.button.actionHandle(controlEvents: .touchUpInside, ForAction: {
            // do what you want when save clicked
            
        })
        //add cancel  button
        addNewListAlert.addAction(self.cancelAction)        
        // 4. Present the alert.
        self.present(addNewListAlert, animated: true, completion: nil)
    }
    `
