### ISSUE TITLE
after update the repo then i got error in SimpleAlert.swift , argument label not match ..

### ISSUE THREAD

**Issue by akmalshukri** [KyoheiG3/SimpleAlert#29]
![screen shot 2017-10-27 at 12 54 01 pm](https://user-images.githubusercontent.com/8844498/32088457-11ea7efc-bb16-11e7-9d0d-1590f1befb96.png)

How to solve this issue ?

**Comment by KyoheiG3** [comment]
Which version's Xcode do you use?

**Comment by akmalshukri** [comment]
xcode 9.1 beta .. but its okay .. already solve it ..
