### ISSUE TITLE
Title & message in AlertController.init(view: ...)

### ISSUE THREAD

**Issue by akabab** [KyoheiG3/SimpleAlert#31]
Hey @KyoheiG3,

how can I have the Title + message view still when I use the AlertController.init(view: ...) initializer.
It's seems that you replace the 'basic view' with the view passed as parameter, is there any way to keep both views? 

Thanks

**Comment by KyoheiG3** [comment]
Hi @akabab 
It cannot keep title with your view. But, I think that's good idea.
Thank you.

**Comment by akabab** [comment]
@KyoheiG3 yeah actually I'd like that to be possible, any idea how to realise it easily ? thanks

**Comment by KyoheiG3** [comment]
It is the easiest that add Title on your view. Or I'm going to try to add View between Contents and Buttons if I had a lot of time to do.

**Comment by KyoheiG3** [comment]
You can also use `configContentView` closure. It can add View on the Alert.

**Comment by KyoheiG3** [comment]
@akabab It's supported in #32 on greater than iOS8.

**Comment by akabab** [comment]
@KyoheiG3 Thanks for the support, is it in a release on cocoapod?

**Comment by KyoheiG3** [comment]
@akabab Yes, you can use it on cocoapods.
