### ISSUE TITLE
Swift 4.2 support 

### ISSUE THREAD

**Issue by Github-Prashant** [KyoheiG3/SimpleAlert#36]
Hi,

I am getting error some swift 4.2 changes like UIControlState change to UIControll.state in swift 4.2. 
Its working fine after changing swift 4 for compilation instead of 4.2. 
Please update Git after compile your source code with Swift 4.2.
I am executing code with Xcode 10.1 through Pod install

**Comment by KyoheiG3** [comment]
Hi @Github-Prashant 
Please check out [3.1.2](https://github.com/KyoheiG3/SimpleAlert/tree/3.1.2) to build at swift 4.2
