### ISSUE TITLE
need to change AlertAction button type to custom instead of system

### ISSUE THREAD

**Issue by sssandyad** [KyoheiG3/SimpleAlert#37]
I need this let variable `public let button = UIButton(type: .system)` in `open class AlertAction` changed to var variable `public var button = UIButton(type: .system)` so that I can override the class and can change the button type

![Screen Shot 2019-03-26 at 17 23 13](https://user-images.githubusercontent.com/6153272/54989973-31ecf600-4fec-11e9-9960-a5481ba5100d.png)

Thank you

**Comment by sssandyad** [comment]
@KyoheiG3

**Comment by KyoheiG3** [comment]
Hi @sssandyad 
Fixed in [3.1.2](https://github.com/KyoheiG3/SimpleAlert/tree/3.1.2).
