### ISSUE TITLE
how to implement didSelect?

### ISSUE THREAD

**Issue by daviddelmonte** [KyoheiG3/SimpleAlert#38]
Nice control. Is there a built-in didSelect process? (IE what button did I press). If not, where do you suggest implementing it. Thanks

**Comment by KyoheiG3** [comment]
`AlertAction` has tap handler that executes when the button was tapped. If you want to know tap events when the button tapped using another method, you can observe the button action that AlertAction has.

**Comment by daviddelmonte** [comment]
Got it. Thanks!
