### ISSUE TITLE
Hidden custom view when neither of title, message or text field is used

### ISSUE THREAD

**Issue by DanPetras** [KyoheiG3/SimpleAlert#39]
From version 5.0.0 it is not possible to see the custom view if I don't set also the title or message.

I try to use it like this
```
let alertView = ...
let alert = AlertController(view: alertView, style: .alert)
let cancelAction = ...
let addAction = ...
alert.addAction(cancelAction)
alert.addAction(addAction)
present(alert, animated: true, completion: nil)
```

But I can see only the buttons.

I located the problem to be here (and next line also):
https://github.com/KyoheiG3/SimpleAlert/blob/057e8330941c8cac798489ce3fbebe8441543476/SimpleAlert/AlertContentView.swift#L29

**Comment by guzhenhuaGitHub** [comment]
It's happened to me, too.
