### ISSUE TITLE
TextField

### ISSUE THREAD

**Issue by ghost** [KyoheiG3/SimpleAlert#4]
How can i use(get) texttfield text after OK button pressed(for example). THANK YOU:)

**Comment by KyoheiG3** [comment]
You can get `textFields` of `alert`:

```
        alert.addAction(SimpleAlert.Action(title: "OK", style: .OK) { action in
            alert.textFields.first?.text
            })
```

**Comment by ghost** [comment]
Cool! Thank You!!!

**Comment by Diego-F-Aguirre** [comment]
Hi Kyo,

How can I enable the multiline feature for the textView? Currently the text stays on one line instead of conforming to the width of the textfield frame and starting a new line.

**Comment by Diego-F-Aguirre** [comment]
Disregard my last, after doing a bit of research I realized UITextfields are not what I want for the multiline feature, I need a UITextView instead. 

Cheers
