### ISSUE TITLE
type of expression is ambiguous without more context 

### ISSUE THREAD

**Issue by lifeisfunny** [KyoheiG3/SimpleAlert#9]
let sle = SimpleAlert.Controller(view: NewPostViewController(), style: .ActionSheet)
the problem happens when define the type of the style   ,

**Comment by KyoheiG3** [comment]
Please pass a sub class of `UIView` to custom view.

https://github.com/KyoheiG3/SimpleAlert/blob/master/SimpleAlertExample/SimpleAlertExample/ViewController.swift#L46
